require("utilfunctions")

require("prototypes.item-groups")
require("prototypes.parts")
require("prototypes.fuel")

require("prototypes.inserters.burner-inserter")
require("prototypes.inserters.long-inserter")
require("prototypes.inserters.fast-inserter")
require("prototypes.inserters.stack-inserter")
require("prototypes.inserters.filter-inserter")
require("prototypes.inserters.stack-filter-inserter")
require("prototypes.inserters.short-long-inserter")
require("prototypes.inserters.long-short-inserter")
require("prototypes.assembling-machines.assembling-machine-1")
require("prototypes.assembling-machines.assembling-machine-2")
require("prototypes.assembling-machines.assembling-machine-3")
require("prototypes.assembling-machines.fuel-assembling-machine")
require("prototypes.mining-drill-2")
require("prototypes.assembling-machines.oil-refinery")
require("prototypes.assembling-machines.chemical-plant")
require("prototypes.pumpjack")
require("prototypes.lab")
require("prototypes.rocket-silo")
require("prototypes.locomotive")

require("prototypes.alternative-recipe")

require("prototypes.electric-technology")
require("prototypes.technology")

require("prototypes.equipment.equipment")
require("prototypes.equipment.energy")
require("prototypes.equipment.armor")
