require("prototypes.item-groups")
require("prototypes.parts")

require("prototypes.burner-inserter")
require("prototypes.long-inserter")
require("prototypes.fast-inserter")
require("prototypes.stack-inserter")
require("prototypes.filter-inserter")
require("prototypes.stack-filter-inserter")
require("prototypes.assembling-machine-1")
require("prototypes.assembling-machine-2")
require("prototypes.assembling-machine-3")
require("prototypes.mining-drill-2")
require("prototypes.oil-refinery")
require("prototypes.chemical-plant")
require("prototypes.pumpjack")
require("prototypes.lab")
require("prototypes.rocket-silo")

require("prototypes.technology")
